# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 982e1706b52882e97be2d8512b04a424640c0048ec6105d33fcfea256b024b70160511f03ff2d8f8d9c6695d913ba49a635c1e2c2616ae131959092f7f4241cc

test:
  secret_key_base: 27b5fabd2e6665c2bfd243206905a63d652670b32f9596267737a1e73e4475457268627fbe41ba5442433a2087e76de838820b8b683647668605f9792acc4b29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
